pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/ankchatu/practice.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                dir('Sample_App_Docker_ECS') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'Sample_App_Docker_ECS/target/*.jar', fingerprint: true
            }
        }

        stage('Run Application (Optional)') {
            steps {
                bat 'java -jar Sample_App_Docker_ECS/target/*.jar'
            }
        }

    }
}
